version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: earendil06/portfolio
      TAG: latest
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $IMAGE_NAME:$TAG .
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Deploy the docker image
          command: docker push $IMAGE_NAME:$TAG

      - run: ssh-keyscan vps.florentpastor.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "d8:8e:cb:71:34:85:58:b0:85:1c:69:06:35:2b:4c:e7"
      - run:
          name: Deploy over SSH
          command: |
            scp docker-compose.yml root@vps.florentpastor.com:~/portfolio
            cd portfolio && docker-compose pull && docker-compose up -d --force-recreate